//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int rensCode { get; set; }
        public int customerId { get; set; }
        public int carCode { get; set; }
        public System.DateTime beginDate { get; set; }
        public System.DateTime finishDate { get; set; }
        public string rentGoal { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
